name: hello_grpc
description: A gRPC server implementation with Android AIDL integration
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  grpc: ^3.1.0
  protobuf: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.hello
        pluginClass: HelloBridge
